// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccqdbzgjcuspwiroltuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjcWRiemdqY3VzcHdpcm9sdHV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MTc0MjcsImV4cCI6MjA2MTk5MzQyN30.A6qNn51qeHHQuoHMY6feqVqZlu2u-6j3HhOkpBh3Q8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);