name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Print repository info
      run: |
        echo "Using repository: https://github.com/swapnil-shahapurkar/DevOps.git"

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Connected to EC2 at $(hostname)"

          # Kill and remove existing container if running
          docker stop vite-app || true
          docker rm vite-app || true

          # Clone repo if not already cloned
          if [ ! -d ~/vite-deploy/.git ]; then
            echo "Cloning from https://github.com/swapnil-shahapurkar/DevOps.git"
            git clone https://github.com/swapnil-shahapurkar/DevOps.git ~/vite-deploy
          fi

          cd ~/vite-deploy
          echo "Inside $(pwd)"
          git pull origin main

          echo "Files in project directory:"
          ls -al

          # Build Docker image
          docker build -t vite-app .

          # Run Docker container
          docker run -d -p 3000:4173 --name vite-app vite-app
        EOF
