name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Print repository info
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Repository owner: ${{ github.repository_owner }}"

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy via SSH
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          echo "Connected to EC2 at $(hostname)"

          # Kill and remove existing container if running
          docker stop vite-app || true
          docker rm vite-app || true

          # Setup GitHub SSH key for private repo access
          mkdir -p ~/.ssh
          echo "${{ secrets.GITHUB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # Clone repo if not exists, otherwise pull latest
          if [ ! -d ~/vite-deploy/.git ]; then
            echo "Cloning repository..."
            git clone git@github.com:${{ github.repository }} ~/vite-deploy
          fi

          cd ~/vite-deploy
          echo "Inside $(pwd)"
          git pull origin main

          echo "Files in project directory:"
          ls -al

          # Build Docker image
          docker build -t vite-app .

          # Run Docker container
          docker run -d -p 3000:4173 --name vite-app vite-app
        EOF
